// Mocks generated by Mockito 5.4.6 from annotations
// in ble_sound_volume/test/mocks/ble_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ble_sound_volume/repositories/ble_repository.dart' as _i2;
import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleRepository extends _i1.Mock implements _i2.BleRepository {
  MockBleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<int> get volumeStream =>
      (super.noSuchMethod(
            Invocation.getter(#volumeStream),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Stream<List<_i4.BluetoothDevice>> scanForDevices() =>
      (super.noSuchMethod(
            Invocation.method(#scanForDevices, []),
            returnValue: _i3.Stream<List<_i4.BluetoothDevice>>.empty(),
          )
          as _i3.Stream<List<_i4.BluetoothDevice>>);

  @override
  _i3.Future<void> connect(_i4.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [device]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVolume(int? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleMute() =>
      (super.noSuchMethod(
            Invocation.method(#toggleMute, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getCurrentVolume() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentVolume, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
